// Code generated by "go run ./cmd/gen-ts"; DO NOT EDIT.
// Source: github.com/meshcore-cz/meshpkt

export interface ErrResult { error: string }

export interface HexResult {
  hex: string;
}
export interface Envelope {
  route: string;
  routeCode: number;
  type: string;
  typeCode: number;
  version: number;
  pathHashSize: number;
  hopCount: number;
  hops: string[];
  payloadHex: string;
  isTransport: boolean;
  transportCodes?: [number, number];
}
export interface GroupTextPayload {
  sender: string;
  text: string;
  timestamp: number;
  txtType: number;
  attempt: number;
  channelHash: string;
}
export interface DirectTextPayload {
  destHash: string;
  srcHash: string;
  text: string;
  timestamp: number;
  txtType: number;
  attempt: number;
}
export interface AdvertPayload {
  publicKey: string;
  timestamp: number;
  name: string;
  nodeType: number;
  hasGPS: boolean;
  lat?: number;
  lon?: number;
}
export interface AckPayload {
  crc: number;
  crcHex: string;
}
export interface GrpDataPayload {
  channelHash: string;
  dataType: number;
  dataHex: string;
}
export interface ReqPayload {
  destHash: string;
  srcHash: string;
  timestamp: number;
  reqType: number;
  dataHex: string;
}
export interface ResponsePayload {
  destHash: string;
  srcHash: string;
  dataHex: string;
}
export interface PathPayload {
  destHash: string;
  srcHash: string;
  path: string[];
  extraType: number;
  extraHex: string;
}
export interface AnonReqPayload {
  destHash: string;
  senderPubKey: string;
  timestamp: number;
  dataHex: string;
}
export interface ControlPayload {
  subType: number;
  flags: number;
  dataHex: string;
  discoverTag?: number;
  discoverTypeFilter?: number;
  discoverSince?: number;
  discoverNodeType?: number;
  discoverSNR?: number;
  discoverPubKey?: string;
}
export interface KeypairResult {
  publicKey: string;
  privateKey: string;
}

export interface MeshcoreWasm {
  encodeGroupText(channelName: string, sender: string, text: string): HexResult | ErrResult;
  encodeGroupTextSecret(secret: string, sender: string, text: string): HexResult | ErrResult;
  encodeGrpData(channelName: string, dataType: number, data: string): HexResult | ErrResult;
  encodeGrpDataSecret(secret: string, dataType: number, data: string): HexResult | ErrResult;
  encodeDirectText(privKey: string, peerPubKey: string, text: string): HexResult | ErrResult;
  encodeAdvert(pubKey: string, signature: string, name: string, hasGPS: number, lat: unknown, lon: unknown): HexResult | ErrResult;
  encodeAck(crc: number): HexResult | ErrResult;
  encodeReq(privKey: string, peerPubKey: string, reqType: number, data: string): HexResult | ErrResult;
  encodeAnonReq(destPubKey: string, myPrivKey: string, data: string): HexResult | ErrResult;
  encodeDiscoverReq(typeFilter: number, tag: number, since: number, prefixOnly: number): HexResult | ErrResult;
  encodeRaw(route: number, payloadType: number, version: number, pathHashSize: number, payload: string): HexResult | ErrResult;
  decodeEnvelope(packet: string): Envelope | ErrResult;
  decodeGroupText(payload: string, channelName: string): GroupTextPayload | ErrResult;
  decodeGroupTextSecret(payload: string, secret: string): GroupTextPayload | ErrResult;
  decodeDirectText(payload: string, privKey: string, peerPubKey: string): DirectTextPayload | ErrResult;
  decodeAdvert(payload: string): AdvertPayload | ErrResult;
  decodeAck(payload: string): AckPayload | ErrResult;
  decodeGrpData(payload: string, channelName: string): GrpDataPayload | ErrResult;
  decodeGrpDataSecret(payload: string, secret: string): GrpDataPayload | ErrResult;
  decodeReq(payload: string, privKey: string, peerPubKey: string): ReqPayload | ErrResult;
  decodeResponse(payload: string, privKey: string, peerPubKey: string): ResponsePayload | ErrResult;
  decodePath(payload: string, privKey: string, peerPubKey: string): PathPayload | ErrResult;
  decodeAnonReq(payload: string, myPrivKey: string): AnonReqPayload | ErrResult;
  decodeControl(payload: string): ControlPayload | ErrResult;
  generateKeypair(): KeypairResult | ErrResult;
  deriveChannelSecret(channelName: string): HexResult | ErrResult;
  sharedSecret(privKey: string, peerPubKey: string): HexResult | ErrResult;
}

export const meshcoreOpNames = [
  "encodeGroupText",
  "encodeGroupTextSecret",
  "encodeGrpData",
  "encodeGrpDataSecret",
  "encodeDirectText",
  "encodeAdvert",
  "encodeAck",
  "encodeReq",
  "encodeAnonReq",
  "encodeDiscoverReq",
  "encodeRaw",
  "decodeEnvelope",
  "decodeGroupText",
  "decodeGroupTextSecret",
  "decodeDirectText",
  "decodeAdvert",
  "decodeAck",
  "decodeGrpData",
  "decodeGrpDataSecret",
  "decodeReq",
  "decodeResponse",
  "decodePath",
  "decodeAnonReq",
  "decodeControl",
  "generateKeypair",
  "deriveChannelSecret",
  "sharedSecret",
] as const

export const RouteTypes = [
  { code: 0, label: "TRANSPORT_FLOOD" },
  { code: 1, label: "FLOOD" },
  { code: 2, label: "DIRECT" },
  { code: 3, label: "TRANSPORT_DIRECT" },
] as const

export const PayloadTypes = [
  { code: 0x00, label: "REQ" },
  { code: 0x01, label: "RESPONSE" },
  { code: 0x02, label: "TXT_MSG" },
  { code: 0x03, label: "ACK" },
  { code: 0x04, label: "ADVERT" },
  { code: 0x05, label: "GRP_TXT" },
  { code: 0x06, label: "GRP_DATA" },
  { code: 0x07, label: "ANON_REQ" },
  { code: 0x08, label: "PATH" },
  { code: 0x09, label: "TRACE" },
  { code: 0x0a, label: "MULTIPART" },
  { code: 0x0b, label: "CONTROL" },
  { code: 0x0f, label: "RAW_CUSTOM" },
] as const
