// Template: copy to your project as cmd/gen-ts/main.go
//
// Generates TypeScript interfaces from meshpkt.Ops for typed window.meshcore calls.
//
// Usage:
//
//	go run ./cmd/gen-ts -out web/src/lib/wasm.gen.ts
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"unicode"

	"github.com/meshcore-cz/meshpkt"
)

func main() {
	out := flag.String("out", "", "output file path (default: stdout)")
	flag.Parse()

	var w io.Writer = os.Stdout
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintln(os.Stderr, "gen-ts:", err)
			os.Exit(1)
		}
		defer f.Close()
		w = f
	}

	if err := generate(w); err != nil {
		fmt.Fprintln(os.Stderr, "gen-ts:", err)
		os.Exit(1)
	}
}

func generate(w io.Writer) error {
	p := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("// Code generated by \"go run ./cmd/gen-ts\"; DO NOT EDIT.")
	p("// Source: github.com/meshcore-cz/meshpkt")
	p("")

	// ErrResult is always present and never comes from an Op.
	p("export interface ErrResult { error: string }")
	p("")

	// ── result interfaces ─────────────────────────────────────────────────────
	// First pass: assign a type name to each unique result shape.
	canonical := map[string]string{}
	opType := map[string]string{}

	for _, op := range meshpkt.Ops {
		key := resultKey(op.Result)
		if name, ok := canonical[key]; ok {
			opType[op.Name] = name
			continue
		}
		name := op.ResultTypeName
		if name == "" {
			name = pascal(op.Name) + "Result"
		}
		canonical[key] = name
		opType[op.Name] = name
	}

	// Second pass: emit one interface per unique shape (in Ops order).
	emitted := map[string]bool{}
	for _, op := range meshpkt.Ops {
		name := opType[op.Name]
		if emitted[name] {
			continue
		}
		emitted[name] = true
		p("export interface %s {", name)
		for _, f := range op.Result {
			opt := ""
			if f.Optional {
				opt = "?"
			}
			p("  %s%s: %s;", f.Name, opt, resultKindTS(f.Kind))
		}
		p("}")
	}
	p("")

	// ── MeshcoreWasm interface ────────────────────────────────────────────────
	p("export interface MeshcoreWasm {")
	for _, op := range meshpkt.Ops {
		params := make([]string, len(op.Params))
		for i, param := range op.Params {
			params[i] = param.Name + ": " + paramKindTS(param.Kind)
		}
		p("  %s(%s): %s | ErrResult;", op.Name, strings.Join(params, ", "), opType[op.Name])
	}
	p("}")
	p("")

	p("export const meshcoreOpNames = [")
	for _, op := range meshpkt.Ops {
		p("  %q,", op.Name)
	}
	p("] as const")
	p("")

	// ── RouteTypes constant ───────────────────────────────────────────────────
	p("export const RouteTypes = [")
	for _, rt := range meshpkt.AllRouteTypes {
		p("  { code: %d, label: %q },", int(rt), rt.String())
	}
	p("] as const")
	p("")

	// ── PayloadTypes constant ─────────────────────────────────────────────────
	p("export const PayloadTypes = [")
	for _, pt := range meshpkt.AllPayloadTypes {
		p("  { code: 0x%02x, label: %q },", int(pt), pt.String())
	}
	p("] as const")
	p("")

	// ── OpMeta interfaces ─────────────────────────────────────────────────────
	p("export interface ParamMeta {")
	p("  name: string;")
	p("  kind: string;")
	p("  label: string;")
	p("  placeholder: string;")
	p("  optional: boolean;")
	p("  choices: { value: number; label: string }[];")
	p("  showWhen: string;")
	p("  showValue: number;")
	p("  group: string;")
	p("  action: string;")
	p("  widget: string;")
	p("  autoFill: string;")
	p("  secret: boolean;")
	p("}")
	p("")
	p("export interface ResultMeta {")
	p("  name: string;")
	p("  kind: string;")
	p("  optional: boolean;")
	p("  label: string;")
	p("}")
	p("")
	p("export interface OpMeta {")
	p("  name: string;")
	p("  category: string;")
	p("  label: string;")
	p("  tabGroup: string;")
	p("  tabGroupLabel: string;")
	p("  tabGroupSub: string;")
	p("  tabGroupDoc: string;")
	p("  tabLabel: string;")
	p("  packetType: string;")
	p("  params: ParamMeta[];")
	p("  result: ResultMeta[];")
	p("  resultTypeName: string;")
	p("}")
	p("")

	// ── OpMetas constant ──────────────────────────────────────────────────────
	p("export const OpMetas: OpMeta[] = [")
	for _, op := range meshpkt.Ops {
		p("  {")
		p("    name: %q,", op.Name)
		p("    category: %q,", op.Category)
		p("    label: %q,", op.Label)
		p("    tabGroup: %q,", op.TabGroup)
		p("    tabGroupLabel: %q,", op.TabGroupLabel)
		p("    tabGroupSub: %q,", op.TabGroupSub)
		p("    tabGroupDoc: %q,", op.TabGroupDoc)
		p("    tabLabel: %q,", op.TabLabel)
		p("    packetType: %q,", op.PacketType)
		p("    resultTypeName: %q,", orDefault(op.ResultTypeName, pascal(op.Name)+"Result"))
		// params
		p("    params: [")
		for _, param := range op.Params {
			p("      {")
			p("        name: %q,", param.Name)
			p("        kind: %q,", paramKindStr(param.Kind))
			p("        label: %q,", param.Label)
			p("        placeholder: %q,", param.Placeholder)
			p("        optional: %v,", param.Optional)
			if len(param.Choices) > 0 {
				p("        choices: [")
				for _, c := range param.Choices {
					p("          { value: %d, label: %q },", c.Value, c.Label)
				}
				p("        ],")
			} else {
				p("        choices: [],")
			}
			p("        showWhen: %q,", param.ShowWhen)
			p("        showValue: %d,", param.ShowValue)
			p("        group: %q,", param.Group)
			p("        action: %q,", param.Action)
			p("        widget: %q,", param.Widget)
			p("        autoFill: %q,", param.AutoFill)
			p("        secret: %v,", param.Secret)
			p("      },")
		}
		p("    ],")
		// result
		p("    result: [")
		for _, rf := range op.Result {
			p("      { name: %q, kind: %q, optional: %v, label: %q },", rf.Name, resultKindStr(rf.Kind), rf.Optional, rf.Label)
		}
		p("    ],")
		p("  },")
	}
	p("]")

	return nil
}

// resultKey produces a canonical string key for a []ResultField so that two
// ops with identical result shapes get the same type.
func resultKey(fields []meshpkt.ResultField) string {
	var sb strings.Builder
	for _, f := range fields {
		fmt.Fprintf(&sb, "%s:%d:%v;", f.Name, f.Kind, f.Optional)
	}
	return sb.String()
}

// pascal uppercases the first rune of s.
func pascal(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func orDefault(s, def string) string {
	if s != "" {
		return s
	}
	return def
}

// paramKindTS maps a ParamKind to its TypeScript type string.
// Both ParamString and ParamHex appear as "string" at the JS boundary.
func paramKindTS(k meshpkt.ParamKind) string {
	switch k {
	case meshpkt.ParamString, meshpkt.ParamHex:
		return "string"
	case meshpkt.ParamInt, meshpkt.ParamFloat:
		return "number"
	default:
		return "unknown"
	}
}

// paramKindStr maps a ParamKind to a short string for OpMeta.
func paramKindStr(k meshpkt.ParamKind) string {
	switch k {
	case meshpkt.ParamString:
		return "string"
	case meshpkt.ParamHex:
		return "hex"
	case meshpkt.ParamInt:
		return "int"
	case meshpkt.ParamFloat:
		return "float"
	default:
		return "unknown"
	}
}

// resultKindTS maps a ResultKind to its TypeScript type string.
func resultKindTS(k meshpkt.ResultKind) string {
	switch k {
	case meshpkt.ResultString:
		return "string"
	case meshpkt.ResultNumber:
		return "number"
	case meshpkt.ResultBool:
		return "boolean"
	case meshpkt.ResultStringArray:
		return "string[]"
	case meshpkt.ResultNumberPair:
		return "[number, number]"
	default:
		return "unknown"
	}
}

// resultKindStr maps a ResultKind to a short string for ResultMeta.
func resultKindStr(k meshpkt.ResultKind) string {
	switch k {
	case meshpkt.ResultString:
		return "string"
	case meshpkt.ResultNumber:
		return "number"
	case meshpkt.ResultBool:
		return "boolean"
	case meshpkt.ResultStringArray:
		return "string[]"
	case meshpkt.ResultNumberPair:
		return "[number, number]"
	default:
		return "unknown"
	}
}
