package meshpkt

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// TestIdentityVectors verifies that Go's SharedSecret matches the recorded
// vectors in testdata/upstream/07a3ca9/identity_vectors.json.
//
// These vectors are generated by the Go implementation itself. Firmware
// interoperability (C++ oracle comparison) is tracked in Milestone 7.
func TestIdentityVectors(t *testing.T) {
	data, err := os.ReadFile("testdata/upstream/07a3ca9/identity_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}

	var v struct {
		AliceSeed    string `json:"alice_seed"`
		AlicePub     string `json:"alice_public"`
		BobSeed      string `json:"bob_seed"`
		BobPub       string `json:"bob_public"`
		SharedSecret string `json:"shared_secret"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}

	aliceSeedBytes, _ := hex.DecodeString(v.AliceSeed)
	bobSeedBytes, _ := hex.DecodeString(v.BobSeed)
	expectedSS, _ := hex.DecodeString(v.SharedSecret)

	var aliceSeed, bobSeed [32]byte
	copy(aliceSeed[:], aliceSeedBytes)
	copy(bobSeed[:], bobSeedBytes)

	alice, err := IdentityFromSeed(aliceSeed)
	if err != nil {
		t.Fatalf("IdentityFromSeed(alice): %v", err)
	}
	bob, err := IdentityFromSeed(bobSeed)
	if err != nil {
		t.Fatalf("IdentityFromSeed(bob): %v", err)
	}

	// Verify public keys match the vectors.
	if hex.EncodeToString(alice.PublicKey[:]) != v.AlicePub {
		t.Errorf("alice public key mismatch:\n  got  %x\n  want %s", alice.PublicKey, v.AlicePub)
	}
	if hex.EncodeToString(bob.PublicKey[:]) != v.BobPub {
		t.Errorf("bob public key mismatch:\n  got  %x\n  want %s", bob.PublicKey, v.BobPub)
	}

	// Verify alice→bob == recorded secret.
	ss1, err := alice.SharedSecret(bob.PublicKey)
	if err != nil {
		t.Fatalf("alice.SharedSecret(bob.PublicKey): %v", err)
	}
	if hex.EncodeToString(ss1[:]) != v.SharedSecret {
		t.Errorf("alice→bob shared secret mismatch:\n  got  %x\n  want %x", ss1, expectedSS)
	}

	// Verify bob→alice == recorded secret.
	ss2, err := bob.SharedSecret(alice.PublicKey)
	if err != nil {
		t.Fatalf("bob.SharedSecret(alice.PublicKey): %v", err)
	}
	if ss1 != ss2 {
		t.Errorf("shared secrets not symmetric:\n  alice→bob: %x\n  bob→alice: %x", ss1, ss2)
	}
}
