package meshpkt

import (
	"crypto/ecdh"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// KeyPair holds a Curve25519 identity keypair.
type KeyPair struct {
	// PublicKey is the hex-encoded 32-byte X25519 public key.
	PublicKey string
	// PrivateKey is the hex-encoded 32-byte X25519 private scalar.
	PrivateKey string
}

// Generate creates a fresh random Curve25519 keypair suitable for use as a
// MeshCore node identity.
func Generate() (KeyPair, error) {
	priv, err := ecdh.X25519().GenerateKey(rand.Reader)
	if err != nil {
		return KeyPair{}, fmt.Errorf("meshpkt: generate: %w", err)
	}
	return KeyPair{
		PublicKey:  hex.EncodeToString(priv.PublicKey().Bytes()),
		PrivateKey: hex.EncodeToString(priv.Bytes()),
	}, nil
}

// Identity is an Ed25519 node identity keypair used for signing ADVERT payloads.
// Real MeshCore devices use Ed25519 keys as their primary identity; this is
// the correct key type for creating signed node advertisements.
//
// Store Seed (32 bytes) to persist and restore the identity.
type Identity struct {
	PublicKey  []byte // 32-byte Ed25519 public key — embed in Advert.PublicKey
	PrivateKey []byte // 64-byte Ed25519 private key (seed ‖ pubkey) — pass to SignAdvertPayload
	Seed       []byte // 32-byte seed — canonical form for storage
}

// GenerateIdentity creates a fresh Ed25519 node identity suitable for MeshCore
// node advertisements.
func GenerateIdentity() (Identity, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return Identity{}, fmt.Errorf("meshpkt: generate identity: %w", err)
	}
	return Identity{
		PublicKey:  []byte(pub),
		PrivateKey: []byte(priv),
		Seed:       priv.Seed(),
	}, nil
}

// IdentityFromSeed restores an Ed25519 identity from its 32-byte seed.
func IdentityFromSeed(seed []byte) (Identity, error) {
	if len(seed) != ed25519.SeedSize {
		return Identity{}, fmt.Errorf("meshpkt: Ed25519 seed must be %d bytes, got %d", ed25519.SeedSize, len(seed))
	}
	priv := ed25519.NewKeyFromSeed(seed)
	return Identity{
		PublicKey:  []byte(priv.Public().(ed25519.PublicKey)),
		PrivateKey: []byte(priv),
		Seed:       seed,
	}, nil
}

// ParsePublicKey validates and decodes a hex-encoded 32-byte X25519 public key.
func ParsePublicKey(hexKey string) ([]byte, error) {
	b, err := hex.DecodeString(hexKey)
	if err != nil {
		return nil, fmt.Errorf("meshpkt: invalid public key: %w", err)
	}
	if len(b) != 32 {
		return nil, fmt.Errorf("meshpkt: public key must be 32 bytes, got %d", len(b))
	}
	if _, err := ecdh.X25519().NewPublicKey(b); err != nil {
		return nil, fmt.Errorf("meshpkt: invalid public key: %w", err)
	}
	return b, nil
}

// ParsePrivateKey validates and decodes a hex-encoded 32-byte X25519 private scalar.
func ParsePrivateKey(hexKey string) ([]byte, error) {
	b, err := hex.DecodeString(hexKey)
	if err != nil {
		return nil, fmt.Errorf("meshpkt: invalid private key: %w", err)
	}
	if len(b) != 32 {
		return nil, fmt.Errorf("meshpkt: private key must be 32 bytes, got %d", len(b))
	}
	if _, err := ecdh.X25519().NewPrivateKey(b); err != nil {
		return nil, fmt.Errorf("meshpkt: invalid private key: %w", err)
	}
	return b, nil
}

// PublicKeyFromPrivate derives the public key from a hex-encoded private scalar.
func PublicKeyFromPrivate(hexPriv string) (string, error) {
	b, err := ParsePrivateKey(hexPriv)
	if err != nil {
		return "", err
	}
	priv, err := ecdh.X25519().NewPrivateKey(b)
	if err != nil {
		return "", fmt.Errorf("meshpkt: %w", err)
	}
	return hex.EncodeToString(priv.PublicKey().Bytes()), nil
}

// SharedSecret performs X25519 ECDH and returns the 32-byte shared secret.
// Callers typically use only the first 16 bytes as an AES-128 key.
//
// Note: real MeshCore identities are Ed25519 keys converted to Montgomery form
// for ECDH. Keys generated by Generate() are native X25519, which are
// self-consistent for the codec tool but may not interoperate with on-air
// MeshCore devices using Ed25519 identities. Verify against firmware
// Identity::calcSharedSecret before relying on direct-message interop.
func SharedSecret(privHex, pubHex string) ([]byte, error) {
	privBytes, err := ParsePrivateKey(privHex)
	if err != nil {
		return nil, err
	}
	pubBytes, err := ParsePublicKey(pubHex)
	if err != nil {
		return nil, err
	}
	curve := ecdh.X25519()
	priv, err := curve.NewPrivateKey(privBytes)
	if err != nil {
		return nil, fmt.Errorf("meshpkt: invalid private key: %w", err)
	}
	pub, err := curve.NewPublicKey(pubBytes)
	if err != nil {
		return nil, fmt.Errorf("meshpkt: invalid public key: %w", err)
	}
	shared, err := priv.ECDH(pub)
	if err != nil {
		return nil, fmt.Errorf("meshpkt: ECDH: %w", err)
	}
	return shared, nil
}
