// Template: copy to your project as cmd/gen-ts/main.go
//
// Generates TypeScript interfaces from meshpkt.Ops for typed window.meshcore calls.
//
// Usage:
//   go run ./cmd/gen-ts -out web/src/lib/wasm.gen.ts
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"unicode"

	"github.com/meshcore-cz/meshpkt"
)

func main() {
	out := flag.String("out", "", "output file path (default: stdout)")
	flag.Parse()

	var w io.Writer = os.Stdout
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintln(os.Stderr, "gen-ts:", err)
			os.Exit(1)
		}
		defer f.Close()
		w = f
	}

	if err := generate(w); err != nil {
		fmt.Fprintln(os.Stderr, "gen-ts:", err)
		os.Exit(1)
	}
}

func generate(w io.Writer) error {
	p := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("// Code generated by \"go run ./cmd/gen-ts\"; DO NOT EDIT.")
	p("// Source: github.com/meshcore-cz/meshpkt")
	p("")

	p("export interface ErrResult { error: string }")
	p("")

	canonical := map[string]string{}
	opType := map[string]string{}

	for _, op := range meshpkt.Ops {
		key := resultKey(op.Result)
		if name, ok := canonical[key]; ok {
			opType[op.Name] = name
			continue
		}
		name := op.ResultTypeName
		if name == "" {
			name = pascal(op.Name) + "Result"
		}
		canonical[key] = name
		opType[op.Name] = name
	}

	emitted := map[string]bool{}
	for _, op := range meshpkt.Ops {
		name := opType[op.Name]
		if emitted[name] {
			continue
		}
		emitted[name] = true
		p("export interface %s {", name)
		for _, f := range op.Result {
			opt := ""
			if f.Optional {
				opt = "?"
			}
			p("  %s%s: %s;", f.Name, opt, resultKindTS(f.Kind))
		}
		p("}")
	}
	p("")

	p("export interface MeshcoreWasm {")
	for _, op := range meshpkt.Ops {
		params := make([]string, len(op.Params))
		for i, param := range op.Params {
			params[i] = param.Name + ": " + paramKindTS(param.Kind)
		}
		p("  %s(%s): %s | ErrResult;", op.Name, strings.Join(params, ", "), opType[op.Name])
	}
	p("}")
	p("")

	p("export const meshcoreOpNames = [")
	for _, op := range meshpkt.Ops {
		p("  %q,", op.Name)
	}
	p("] as const")
	p("")

	p("export const RouteTypes = [")
	for _, rt := range meshpkt.AllRouteTypes {
		p("  { code: %d, label: %q },", int(rt), rt.String())
	}
	p("] as const")
	p("")

	p("export const PayloadTypes = [")
	for _, pt := range meshpkt.AllPayloadTypes {
		p("  { code: 0x%02x, label: %q },", int(pt), pt.String())
	}
	p("] as const")

	return nil
}

func resultKey(fields []meshpkt.ResultField) string {
	var sb strings.Builder
	for _, f := range fields {
		fmt.Fprintf(&sb, "%s:%d:%v;", f.Name, f.Kind, f.Optional)
	}
	return sb.String()
}

func pascal(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func paramKindTS(k meshpkt.ParamKind) string {
	switch k {
	case meshpkt.ParamString, meshpkt.ParamHex:
		return "string"
	case meshpkt.ParamInt:
		return "number"
	default:
		return "unknown"
	}
}

func resultKindTS(k meshpkt.ResultKind) string {
	switch k {
	case meshpkt.ResultString:
		return "string"
	case meshpkt.ResultNumber:
		return "number"
	case meshpkt.ResultBool:
		return "boolean"
	case meshpkt.ResultStringArray:
		return "string[]"
	case meshpkt.ResultNumberPair:
		return "[number, number]"
	default:
		return "unknown"
	}
}
